### ISSUE TITLE
Watt Meter: KeyError: 'sppower_current_amperage'

### ISSUE THREAD

**Issue by ssbarnea** [matryer/xbar-plugins#1176]
imac:~ ssbarnea$ /Users/ssbarnea/Library/Mobile\ Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py
Traceback (most recent call last):
  File "/Users/ssbarnea/Library/Mobile Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py", line 78, in <module>
    main()
  File "/Users/ssbarnea/Library/Mobile Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py", line 65, in main
    machine = parse_system_profiler()
  File "/Users/ssbarnea/Library/Mobile Documents/com~apple~CloudDocs/configs/bitbar/watt-meter.20s.py", line 43, in parse_system_profiler
    "current_amperage": int(spbattery_info['sppower_current_amperage']),
KeyError: 'sppower_current_amperage'
imac:~ ssbarnea$ 

FAO: (@eripa)

**Comment by capitolmatt22** [comment]
Also getting this issue on a 2019 MacBook pro with Monteray

**Comment by gingerbeardman** [comment]
closing as dupe of #1176

**Comment by gingerbeardman** [comment]
@eripa this plugin no longer works on the latest macOS, where output format of system profiler has changed and Apple silicon CPUs are reported in a different way.

Details at: matryer/xbar#849
