### ISSUE TITLE
re: Stock Ticker

### ISSUE THREAD

**Issue by merkrebs** [matryer/xbar-plugins#1427]
FAO: (@rkanter)
When I add Stock Ticker, BitBar shows a yellow triangle alert in the menu bar.
MacOS Catalina 10.15.4
iMac (Retina 5K, 27-inch,2017)
Processor 4.2 GHz Quad-Core Intel Core i7
Memory 32 GB 2400 MHz DDR4
Graphics Radeon Pro 580 8 GB

Last login: Mon Apr 27 10:02:33 on ttys001

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Users/alm/Documents/BitBar\ Plugins/stock-ticker.30s.py
iMac-27:~ alm$ /Users/alm/Documents/BitBar\ Plugins/stock-ticker.30s.py
Traceback (most recent call last):
  File "/Users/alm/Documents/BitBar Plugins/stock-ticker.30s.py", line 26, in <module>
    response = urllib2.urlopen("https://cloud.iexapis.com/stable/stock/market/batch?symbols=" + ','.join(stock_symbols) + "&types=quote&filter=symbol,latestPrice,change,changePercent&displayPercent=true&token=" + api_token)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
iMac-27:~ alm$

**Comment by rkanter** [comment]
Unfortunately, the API requires you to create a (free) account and get an API token that you need to put into the script.  The directions for that are in the script itself, here:
https://github.com/matryer/bitbar-plugins/blob/master/Finance/stock-ticker.30s.py#L14-L20
