### ISSUE TITLE
github contribution plugin issue

### ISSUE THREAD

**Issue by Juhyeoklee** [matryer/xbar-plugins#1550]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/43847166/107063111-54254100-681d-11eb-98af-15e9266f3421.png">

I have problem with refresh my github contribution plugin ..

Please help

**Comment by anthonyminyungi** [comment]
The same issue occurred to me a while ago.
I don't know the cause of this issue and how to fix it.

**Comment by rtud** [comment]
I'm getting the same issue:

```
> ./github-contribution.10m.rb
Traceback (most recent call last):
	4: from ./github-contributions.10m.rb:192:in `<main>'
	3: from ./github-contributions.10m.rb:164:in `run'
	2: from ./github-contributions.10m.rb:164:in `new'
	1: from ./github-contributions.10m.rb:139:in `initialize'
./github-contributions.10m.rb:139:in `fetch': index 0 outside of array bounds: 0...0 (IndexError)
```

**Comment by matryer** [comment]
@Juhyeoklee Can you mention the author (should be in the metadata inside the plugin)

**Comment by geeknees** [comment]
I was able to fix it by changing the code around line 81 as follows
I am not the author, but I can create a PR for you if you need it.

```rb
    class Contribution < Struct.new(:username, :contributed_on, :count)
      RE_CONTRIBUTION = %r|<rect .*class="ContributionCalendar-day" .*data-date="(\d\d\d\d-\d\d-\d\d)" .*data-level="(\d+)" .*>.*<\/rect>|

      def self.find_all_by(username:)
        [].tap do |contributions|
          html = URI.parse(url_for(username: username)).open { |f| f.read }
          html.scan(RE_CONTRIBUTION) do |date, count|
            contributions << Contribution.new(username, Date.parse(date), count.to_i)
            break if Date.parse(date) == Date.parse(DateTime.now.to_s)
          end
        end
      end

      def color
        count <= 0 ? 'brown' : 'green'
      end

      def icon
        case count
        when 0    then '👻'
        when 1..3 then '🌱'
        when 4..9 then '🌿'
        else           '🌳'
        end
      end

      def self.url_for(username:)
        "https://github.com/users/#{username}/contributions"
      end
    end
```

**Comment by sprak3000** [comment]
Updated the plugin based on @geeknees patch. Works great! Also, I used xbar variables to allow easy configuration of username and max contributions.
