### ISSUE TITLE
001-kubecontext.1s.py: 

### ISSUE THREAD

**Issue by 17812** [matryer/xbar-plugins#1797]
fao @copland - Hi - getting the error  below after latest 12.3 MacOS upgrade

Traceback (most recent call last):
  File "/Users/tolga/Library/Application Support/xbar/plugins/001-kubecontext.1s.py", line 60, in <module>
    CONTEXTS = load_contexts()
  File "/Users/tolga/Library/Application Support/xbar/plugins/001-kubecontext.1s.py", line 34, in load_contexts
    lines = out.split('\n')
TypeError: a bytes-like object is required, not 'str'

**Comment by 17812** [comment]
hey..  after casting subprocess .checkoutput(cmd)  to byte and decoding to string for vardict, issue is resolved.
