### ISSUE TITLE
001-sureflap.15s.rb: 

### ISSUE THREAD

**Issue by kilkern** [matryer/xbar-plugins#2043]
fao @henrik - 
The sureflap app in Xbar appear to have stopped working.
Error message: 
`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' (JSON::ParserError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:130:in `block in get'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:80:in `handle_network_errors'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:121:in `get'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:176:in `block (2 levels) in <main>'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:171:in `map'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:171:in `block in <main>'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:156:in `with_fresh_token'
	from /Users/rune/Library/Application Support/xbar/plugins/001-sureflap.15s.rb:166:in `<main>'`
	
I have tested with Ruby 3.3.1, and that give the same/similar error. 

Hope you have the time to assist.

**Comment by henrik** [comment]
Not sure off the top of my head, other than it looks like it expects JSON but gets an empty string.

I'm afraid I'm not using the SureFlap anymore (got the OnlyCat) so I don't plan on maintaining this plugin. Sorry about that!

**Comment by sprak3000** [comment]
Closing due to age and author no longer supporting plugin.
